[general]
live_config_reload = true

# FONT
[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

size = 16.0
